networks:
    pyhss:
        name: pyhss
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}
        driver_opts:
            com.docker.network.bridge.name: pyhss

services:
    mariadb:
        image: bitnami/mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD?db root password required}
            MARIADB_DATABASE: ${DB_NAME?db name required}
            MARIADB_USER: ${DB_USER?db user required}
            MARIADB_PASSWORD: ${DB_PASSWORD?db password required}
        volumes:
            - mariadb_data:/bitnami/mariadb
        networks:
            pyhss:
                ipv4_address: ${MARIADB_IP}
    redis:
        image: bitnami/redis:latest
        container_name: redis
        restart: always
        volumes:
            - redis_data:/bitnami/redis
        networks:
            pyhss:
                ipv4_address: ${REDIS_IP}

    pyhss:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        image: 0rigina1/pyhss:v1.0.0
        container_name: pyhss
        environment:
            COMPONENT_NAME: ${COMPONENT_NAME}
        volumes:
            - ./pyhss:/mnt/hss
        expose:
            - "3868/tcp"
            - "3868/sctp"
        ports:
            - "3868:3868/tcp"
            - "3868:3868/sctp"
        depends_on:
            - mariadb
            - redis
        networks:
            pyhss:
                ipv4_address: ${HSS_IP}

volumes:
    mariadb_data:
    redis_data:
